### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by Tamaralb** [alptium/tamara.sevic#2]

**Comment by valentinacupac** [comment]
@Tamaralb, please check that you have exactly followed all the instructions in https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World e.g. in step 1, it say to assign the ticket to yourself and also in 9. writing a comment to me, so please review those and all the other steps.

**Comment by valentinacupac** [comment]
@Tamaralb, I cannot open the project in Eclipse, I cannot see the hello-world project in your repository, but only calculator... please can you check again where you saved your project. See example from my repository https://github.com/alptium/valentina.cupac where you can see the folder hello-world...

**Comment by Tamaralb** [comment]
@valentinacupac  Can you see now my hello-world project?

**Comment by valentinacupac** [comment]
@Tamaralb:

Please **delete** the following files because you had created them accidentally first time when experimenting with Eclipse, they should not be there:

1. tamara.sevic\bin
2. tamara.sevic\src
3. tamara.sevic\.classpath
4. tamara.sevic\.project

Reason is, those should be only with projects and not within your root.

Furthermore inside https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World see my comments 1., 2. and 11.

**Comment by Tamaralb** [comment]
@valentinacupac  You can review this task.

**Comment by valentinacupac** [comment]
@Tamaralb: 
1. You forgot to delete tamara.sevic\bin (see my comment above).
2. Delete the folder Helloworld (because you only should have hello-world)
3. See https://github.com/alptium/valentina.cupac/wiki/03.-Hello-World review comment 11.
4. In lines System.out.println, please go a tab to the left, see my example https://github.com/alptium/valentina.cupac/blob/master/hello-world/src/org/alptium/valentinacupac/samples/helloworld/Main.java (this is about style and formatting, you had an extra tab on those lines)

**Comment by valentinacupac** [comment]
@Tamaralb:
1. There needs to be a "try" block around the scanner, see my example https://github.com/alptium/valentina.cupac/blob/master/calculator/src/org/alptium/valentinacupac/samples/calculator/Main.java
2. Regarding formatting, when you have operations like = there should be a space before and after, see my example
3. Regarding formatting there should be a space between } and else if
4. Regarding formatting after } there should be an empty lin, see line 30 in your code

Let me know if this is clear or any clarification required.

**Comment by Tamaralb** [comment]
@valentinacupac You can review this task.

**Comment by valentinacupac** [comment]
@Tamaralb, it's correct now.
